name: genetic_algorithm
description: It is fast, easy to use and extensable genetic algorithm implementaion for dart.
version: 1.0.0
repository: https://github.com/noormajzoob/genetic_algorithm

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
